name: CI

on:
  - push

jobs:
  test:
    name: lint
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Configure Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run lint
      - run: npm run lint -- --config react.js
      - run: npm run lint -- --config typescript.js
