name: CI

on:
  - push

jobs:
  test:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run lint
      - run: npm run lint:prettier
      - run: npm run lint:react
      - run: npm run lint:typescript
